import type { Project } from "@/types";
import { withBasePath } from "@/lib/utils";

export const projects: Project[] = [
  {
    id: "p-elios",
    slug: "elios-wholesale",
    year: "2026",
    title: "Elios Wholesale",
    tagline:
      "A high-performance B2B logistics & import dashboard bridging wholesale trade between China and India.",
    overview:
      "Elios Wholesale is a custom logistics and B2B import management dashboard built for an international trading client. The platform streamlines multi-currency payments (INR & CNY), tracks shipments through active transit states, coordinates customs documentation, and features a photo-based sourcing request pipeline.",
    features: [
      "Custom import order tracking from sourcing and repacking/QC to customs clearance and final delivery",
      "Dual-currency accounting system displaying transaction amounts in INR (₹) and CNY (¥) dynamically",
      "Photo-upload sourcing requests, allowing clients to request price quotes by uploading product pictures",
      "Real-time logistics pipeline map showing shipment locations and ETA updates",
      "Client dashboard with order statistics, pending quotes, active transit tallies, and exception alerts",
    ],
    challenges: [
      "Designing a robust state-syncing pipeline for complex multi-leg shipping journeys spanning international borders",
      "Optimizing multi-currency calculations and ensuring precise formatting across INR and CNY transaction ledgers",
      "Implementing a seamless photo-request flow that processes and indexes image uploads for fast back-office sourcing",
    ],
    tech: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Lucide Icons"],
    accent: "blue",
    role: "Freelance Developer",
    duration: "1 month",
    cover: withBasePath("/images/projects/elios-wholesale.jpg"),
    gallery: [
      withBasePath("/images/projects/elios-wholesale.jpg"),
    ],
    featured: true,
    status: "Client Project",
    links: {
      live: "https://www.elioswholesale.in/login",
      github: "https://github.com/palaashika26-bot/elioswholesale",
    },
  },
  {
    id: "p-quizbattle",
    slug: "quizbattle-ai",
    year: "2026",
    title: "QuizBattle AI",
    tagline:
      "An AI-powered dynamic quiz platform generating personalized assessments using Llama 3.3.",
    overview:
      "QuizBattle AI is an interactive web-based quiz application that utilizes artificial intelligence to generate customized assessments on the fly. Users can input any topic and specify question count, and the platform interfaces with a Python Flask backend to retrieve schema-validated questions generated by Llama 3.3 via the Groq API.",
    features: [
      "On-demand AI question generation for any topic using the Llama 3.3 70B model via Groq API",
      "Strict JSON schema enforcement using system prompts to guarantee clean frontend rendering",
      "Interactive gameplay UI displaying real-time feedback, animations, and point scoring",
      "Dual-backend architecture with a Python Flask server and a PHP fallback API for versatile hosting",
      "Responsive scoreboards and game state management in vanilla HTML/CSS/JS",
    ],
    challenges: [
      "Enforcing AI outputs to strictly conform to JSON array syntax without markdown wrapper blocks",
      "Managing CORS configurations and API latency spikes during high-volume Groq API calls",
      "Implementing a seamless transition flow for questions and animations on the client side",
    ],
    tech: ["Python", "Flask", "Groq API", "Llama 3.3", "JavaScript", "HTML5", "CSS3", "PHP"],
    accent: "cyan",
    role: "Full-Stack Developer",
    duration: "2 weeks",
    cover: withBasePath("/images/projects/quizbattle-ai.png"),
    gallery: [
      withBasePath("/images/projects/quizbattle-ai.png"),
    ],
    featured: false,
    status: "AI Web App",
    links: {
      live: "https://quiz-battle-ai.onrender.com/",
      github: "https://github.com/palaashika26-bot/quiz-battle-ai",
    },
  },
  {
    id: "p-tictactoe",
    slug: "tic-tac-toe",
    year: "2025",
    title: "Tic Tac Toe",
    tagline:
      "A sleek, high-fidelity classic game with smooth state management and neon-themed grid animations.",
    overview:
      "Tic Tac Toe is a modern take on the classic paper-and-pencil game, built to showcase responsive DOM manipulation and interactive CSS animation. The game manages state transitions locally in the browser, tracking turns, victory patterns, and draws cleanly.",
    features: [
      "Responsive grid layout adapts to different mobile and desktop device screen sizes",
      "Dynamic CSS classes for neon blue 'O' and neon pink 'X' custom highlights",
      "Robust victory algorithm checking 8 distinct winning line patterns in real-time",
      "Smooth state resets, keeping player stats and grids aligned instantly",
    ],
    challenges: [
      "Designing clean, scale-independent grid elements using modern CSS Flexbox and Grid layout systems",
      "Optimizing turn toggling logic and win detection algorithms for zero-latency browser response",
    ],
    tech: ["HTML5", "CSS3", "JavaScript"],
    accent: "emerald",
    role: "Frontend Developer",
    duration: "3 days",
    cover: withBasePath("/images/projects/tic-tac-toe.png"),
    gallery: [
      withBasePath("/images/projects/tic-tac-toe.png"),
    ],
    featured: false,
    status: "Game",
    links: {
      live: "https://palaashika26-bot.github.io/tic-tac-toe/",
      github: "https://github.com/palaashika26-bot/tic-tac-toe",
    },
  },
  {
    id: "p-rockpaperscissors",
    slug: "rock-paper-scissors",
    year: "2025",
    title: "Rock Paper Scissors",
    tagline:
      "An animated browser-based game featuring artificial delays and interactive shake effects.",
    overview:
      "Rock Paper Scissors is an interactive frontend game designed with engaging micro-interactions. The game features an artificial thinking delay to build tension, custom shake animations on selection, and persistent scoreboards tracking wins, losses, and draws.",
    features: [
      "Interactive game choice selectors (Rock, Paper, Scissors) with active border glowing highlights",
      "Smooth shake animations and animated score counter pops to enhance the player visual response",
      "Simulated 'computer thinking' delay using asynchronous JavaScript states",
      "Persistent scoreboard tracking wins, losses, and draws throughout the gaming session",
    ],
    challenges: [
      "Managing async browser state to disable input during shake animations and prevent click spamming",
      "Creating reusable CSS keyframe animations that reset consistently across browser reflow cycles",
    ],
    tech: ["HTML5", "CSS3", "JavaScript", "Keyframe Animations"],
    accent: "rose",
    role: "Frontend Developer",
    duration: "5 days",
    cover: withBasePath("/images/projects/rock-paper-scissors.png"),
    gallery: [
      withBasePath("/images/projects/rock-paper-scissors.png"),
    ],
    featured: false,
    status: "Game",
    links: {
      live: "https://palaashika26-bot.github.io/rock_paper_scissors/",
      github: "https://github.com/palaashika26-bot/rock_paper_scissors",
    },
  },
];
